import { Course } from './types'

const B = (id: string) => `https://iframe.mediadelivery.net/embed/671872/${id}`

export const DEMO_COURSE: Course = {
  id: 'course-1',
  title: 'إتقان المونتاج: Premiere Pro & After Effects',
  description: 'دورة شاملة من الصفر إلى الاحتراف في مجال المونتاج الرقمي',
  is_active: true,
  created_at: new Date().toISOString(),
  modules: [

    // ══════════════════════════════════════════
    //  الوحدة 1 — Premiere Pro: الجانب النظري
    // ══════════════════════════════════════════
    {
      id: 'mod-1',
      course_id: 'course-1',
      title: 'Premiere Pro — الجانب النظري',
      order_index: 1,
      created_at: new Date().toISOString(),
      lessons: [
        {
          id: 'les-1-1',
          module_id: 'mod-1',
          title: 'التقديم: أهمية المونتاج',
          description: 'مقدمة عن عالم المونتاج وأهميته في السوق الرقمي',
          video_url: B('51f16ae0-63ce-4bae-b323-bde867083619'),
          duration_seconds: 600,
          order_index: 1,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-2',
          module_id: 'mod-1',
          title: 'كم ستربح من المونتاج',
          description: 'الدخل المتوقع ونماذج الكسب من مهارة المونتاج',
          video_url: B('0418c689-9a08-4696-9742-f85e816e891a'),
          duration_seconds: 720,
          order_index: 2,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-3',
          module_id: 'mod-1',
          title: 'لماذا تحرير الفيديو هو أهم مجال',
          description: 'أسباب تفوق مجال المونتاج وطلبه المتزايد',
          video_url: B('d2d90bd0-9e19-4fe1-aceb-0126f5d39149'),
          duration_seconds: 600,
          order_index: 3,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-4',
          module_id: 'mod-1',
          title: 'قيمتك كمحرر فيديو ستزداد أكثر',
          description: 'كيف ترفع قيمتك المهنية وتفرض سعرك',
          video_url: B('568f797a-5ce2-43ea-8924-5f0925eecece'),
          duration_seconds: 660,
          order_index: 4,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-5',
          module_id: 'mod-1',
          title: 'العقلية',
          description: 'العقلية الصحيحة للنجاح في مجال المونتاج',
          video_url: B('894dce03-2f4a-4218-90a5-d6f8408b59c9'),
          duration_seconds: 480,
          order_index: 5,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-6',
          module_id: 'mod-1',
          title: 'ماذا ستحتاج للبدء في المجال',
          description: 'الأدوات والمتطلبات الأساسية لبدء مسيرتك',
          video_url: B('060abfe9-ce10-4718-bd7e-0ef7d75b4c65'),
          duration_seconds: 540,
          order_index: 6,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-7',
          module_id: 'mod-1',
          title: 'أين أجد Premiere Pro',
          description: 'طريقة الحصول على البرنامج وتثبيته',
          video_url: B('cd28113b-6289-41cb-9513-39427132b8cf'),
          duration_seconds: 480,
          order_index: 7,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-1-8',
          module_id: 'mod-1',
          title: 'طريقة إيجاد أول عميل',
          description: 'خطوات عملية للحصول على أول عميل في مجال المونتاج',
          video_url: B('97e54fd9-28e3-4e06-88e9-bc2ba0e85cce'),
          duration_seconds: 900,
          order_index: 8,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
      ],
    },

    // ════════════════════════════════════════════
    //  الوحدة 2 — Premiere Pro: الجانب التطبيقي
    // ════════════════════════════════════════════
    {
      id: 'mod-2',
      course_id: 'course-1',
      title: 'Premiere Pro — الجانب التطبيقي',
      order_index: 2,
      created_at: new Date().toISOString(),
      lessons: [
        {
          id: 'les-2-1',
          module_id: 'mod-2',
          title: 'ثلاث طرق لكسب عملاء جدد',
          description: 'استراتيجيات فعّالة لاستقطاب العملاء باستمرار',
          video_url: B('becfe150-a084-4a85-8104-948ef3bd3609'),
          duration_seconds: 900,
          order_index: 1,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-2',
          module_id: 'mod-2',
          title: 'تنظيم الملفات',
          description: 'أفضل طريقة لتنظيم مشاريعك وملفاتك داخل البرنامج',
          video_url: B('007073e8-67c9-4b3b-92a2-67be26c75de5'),
          duration_seconds: 720,
          order_index: 2,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-3',
          module_id: 'mod-2',
          title: 'شرح واجهة البرنامج',
          description: 'جولة شاملة في كل أجزاء Premiere Pro',
          video_url: B('636865ce-8121-48a2-8d67-b9f0f0b5b376'),
          duration_seconds: 1200,
          order_index: 3,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-4',
          module_id: 'mod-2',
          title: 'فهم خصائص المقاطع والإطارات',
          description: 'كل ما تحتاج معرفته عن المقاطع والـ Frames',
          video_url: B('d331dbb2-d3ea-4184-9d5a-983e27a8da37'),
          duration_seconds: 1080,
          order_index: 4,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-5',
          module_id: 'mod-2',
          title: 'إنشاء مشروع جديد داخل البرنامج',
          description: 'خطوات إنشاء مشروع بالإعدادات الصحيحة',
          video_url: B('ce2eb3ff-c02c-48ef-a450-c9dd5df41aeb'),
          duration_seconds: 840,
          order_index: 5,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-6',
          module_id: 'mod-2',
          title: 'ضبط الصوت ودمجه مع الفيديو',
          description: 'تقنيات ضبط الصوت وتنسيقه مع الصورة',
          video_url: B('8e4d5560-e571-43fe-918e-bdea3f515eeb'),
          duration_seconds: 1200,
          order_index: 6,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-7',
          module_id: 'mod-2',
          title: 'شرح الأزرار ومعناها',
          description: 'فهم كل أزرار البرنامج ووظيفة كل منها',
          video_url: B('ef034cb9-b9e5-4933-8424-dd744980000c'),
          duration_seconds: 960,
          order_index: 7,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-8',
          module_id: 'mod-2',
          title: 'القص واللصق',
          description: 'إتقان تقنيات القص واللصق الاحترافي',
          video_url: B('97e54fd9-28e3-4e06-88e9-bc2ba0e85cce'),
          duration_seconds: 1080,
          order_index: 8,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-9',
          module_id: 'mod-2',
          title: 'أسرار الاختصارات التي تسرع عملك',
          description: 'اختصارات لوحة المفاتيح التي يستخدمها المحترفون',
          video_url: B('3e0bb5ff-4933-44ce-9bd9-1a596ea96ccb'),
          duration_seconds: 900,
          order_index: 9,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-10',
          module_id: 'mod-2',
          title: 'فيديو تطبيقي لفهم الأساسيات',
          description: 'تطبيق عملي شامل لكل ما تعلمته',
          video_url: B('e52b0e04-6e55-4f77-b02b-7cf0d1ebbba7'),
          duration_seconds: 2400,
          order_index: 10,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-11',
          module_id: 'mod-2',
          title: 'طريقة الكتابة على الفيديو',
          description: 'إضافة نصوص وعناوين احترافية على الفيديو',
          video_url: B('3594077a-f451-4ada-8a1a-420a400d51de'),
          duration_seconds: 1080,
          order_index: 11,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-12',
          module_id: 'mod-2',
          title: 'إضافة مؤثرات صوتية مناسبة',
          description: 'اختيار المؤثرات الصوتية وتركيبها بشكل احترافي',
          video_url: B('f94531fe-4886-4203-aedf-e487af17a063'),
          duration_seconds: 960,
          order_index: 12,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-13',
          module_id: 'mod-2',
          title: 'تلوين الفيديو بطريقة احترافية',
          description: 'Color Grading واللوت والتصحيح اللوني',
          video_url: B('60d08e0f-10fe-4a15-b7da-af1a5e66961b'),
          duration_seconds: 1800,
          order_index: 13,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-2-14',
          module_id: 'mod-2',
          title: 'أفضل إعدادات تصدير الفيديو',
          description: 'إعدادات التصدير المثالية لكل منصة',
          video_url: B('29b0f09b-a733-40e9-8ee1-51394a2e3dd7'),
          duration_seconds: 1200,
          order_index: 14,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
      ],
    },

    // ══════════════════════════════════
    //  الوحدة 3 — After Effects
    // ══════════════════════════════════
    {
      id: 'mod-3',
      course_id: 'course-1',
      title: 'After Effects — من الصفر',
      order_index: 3,
      created_at: new Date().toISOString(),
      lessons: [

        // — النظري —
        {
          id: 'les-3-1',
          module_id: 'mod-3',
          title: 'التقديم',
          description: 'مقدمة إلى After Effects وما ستتعلمه في هذه الوحدة',
          video_url: B('9ae00165-fe18-45a1-b7b5-69713e8664dc'),
          duration_seconds: 480,
          order_index: 1,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-2',
          module_id: 'mod-3',
          title: 'الفرق بين Premiere Pro وAfter Effects',
          description: 'متى تستخدم كل برنامج وكيف يكملان بعضهما',
          video_url: B('86a5508d-6c9c-4469-975c-c0be0a1b3405'),
          duration_seconds: 720,
          order_index: 2,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-3',
          module_id: 'mod-3',
          title: 'تحميل البرنامج',
          description: 'طريقة الحصول على After Effects وتثبيته',
          video_url: B('b1e80537-4083-4c23-97a0-f648c6bf640c'),
          duration_seconds: 480,
          order_index: 3,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-4',
          module_id: 'mod-3',
          title: 'شرح واجهة البرنامج',
          description: 'جولة شاملة في كل أجزاء After Effects',
          video_url: B('63a76491-f4ee-49aa-aa3d-6af3fdd2f0fc'),
          duration_seconds: 1200,
          order_index: 4,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-5',
          module_id: 'mod-3',
          title: 'شرح واجهة البرنامج 2',
          description: 'تعمق أكثر في واجهة After Effects والأدوات المتقدمة',
          video_url: B('213ac4b6-c5a6-481d-878e-9af67c8c4ec9'),
          duration_seconds: 1200,
          order_index: 5,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-6',
          module_id: 'mod-3',
          title: 'Selection Objects PNG',
          description: 'كيفية اختيار وتحريك عناصر PNG في After Effects',
          video_url: B('ab8e3737-ee7b-43ee-8f5e-61176ac59268'),
          duration_seconds: 900,
          order_index: 6,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-7',
          module_id: 'mod-3',
          title: 'Selection Objects PNG 2',
          description: 'تقنيات متقدمة في التعامل مع ملفات PNG',
          video_url: B('0cbc65b2-87af-47e9-ac04-2fc3d3ef404f'),
          duration_seconds: 900,
          order_index: 7,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-8',
          module_id: 'mod-3',
          title: 'Selection Objects PNG 3',
          description: 'إتقان التعامل مع ملفات PNG في المشاريع الاحترافية',
          video_url: B('b2dee57f-781c-46d7-bb7b-45c9f1e2d249'),
          duration_seconds: 900,
          order_index: 8,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-9',
          module_id: 'mod-3',
          title: 'كيفية الحصول على الزبناء',
          description: 'كيف تستهدف عملاء After Effects وتقنع بخدماتك',
          video_url: B('4796d0db-5345-47ce-8e5b-e7875c484c1c'),
          duration_seconds: 900,
          order_index: 9,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-10',
          module_id: 'mod-3',
          title: 'أهمية الاستمرارية',
          description: 'كيف تبني مسيرة مهنية مستدامة في مجال المونتاج',
          video_url: B('7693836a-c4cd-40c3-836c-ae4d18262a7e'),
          duration_seconds: 720,
          order_index: 10,
          is_preview: false,
          created_at: new Date().toISOString(),
        },

        // — الجانب التطبيقي —
        {
          id: 'les-3-11',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 1',
          description: 'تطبيق عملي على After Effects — الجزء الأول',
          video_url: B('8ad5910d-72cd-4652-993c-328af3886bdb'),
          duration_seconds: 3600,
          order_index: 11,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-12',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 2',
          description: 'تطبيق عملي على After Effects — الجزء الثاني',
          video_url: B('1e61cefb-9009-4edb-b359-cbe80504d0a0'),
          duration_seconds: 3600,
          order_index: 12,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-13',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 3',
          description: 'تطبيق عملي على After Effects — الجزء الثالث',
          video_url: B('e5e20499-bc42-48c2-8f2c-5f9358bfc7c7'),
          duration_seconds: 3600,
          order_index: 13,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-14',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 4',
          description: 'تطبيق عملي على After Effects — الجزء الرابع',
          video_url: B('691d02ff-da42-42c4-b933-6bb957026864'),
          duration_seconds: 3600,
          order_index: 14,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-15',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 5',
          description: 'تطبيق عملي على After Effects — الجزء الخامس',
          video_url: B('c78ae5d0-33e4-48d7-ba63-c67c4a5e87f5'),
          duration_seconds: 3600,
          order_index: 15,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-16',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 6',
          description: 'تطبيق عملي على After Effects — الجزء السادس',
          video_url: B('67354597-c7ce-4585-a29f-b63e5cdf39e4'),
          duration_seconds: 3600,
          order_index: 16,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-17',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 7',
          description: 'تطبيق عملي على After Effects — الجزء السابع',
          video_url: B('3164cf11-93bc-4f1b-9abf-d432be4a98b4'),
          duration_seconds: 3600,
          order_index: 17,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
        {
          id: 'les-3-18',
          module_id: 'mod-3',
          title: 'الجانب التطبيقي 8',
          description: 'تطبيق عملي على After Effects — الجزء الثامن والأخير',
          video_url: B('076cee1c-9f4f-418f-a360-f1896b5f0c73'),
          duration_seconds: 3600,
          order_index: 18,
          is_preview: false,
          created_at: new Date().toISOString(),
        },
      ],
    },
  ],
}
